application: wiki-it
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /googlea14ae9cf3d54ab79.html
  static_files: googlea14ae9cf3d54ab79.html
  upload: googlea14ae9cf3d54ab79.html
  
- url: .*
  script: wiki_it.wsgi.application

libraries:
- name: django
  version: "1.4"
